<h3>Contenido</h3> 
<br/> 
<h1>Bienvenidos a nuestra página!</h1> 
<p> 
Esta Página ha sido maquetada con twitter bootstrap 
</p> 
<p><a href="<?php echo $this->baseUrl('/ChefLeonardoChacon');  ?>" class="btn btn-primary btn-large">Mas información</a></p> 

<?php echo $this->htmlFlash($this->baseUrl('/flash/intro.swf'),
                array('width' => 500, 'height' => 400)
                );
                ?>

<br>
Leonardo Chacón Fernández
<br>
Creador de la cocina patagónica ®
<br>
Pionero en el desarrollo de la cocina regional chilena, celebra 50 años de 
<br>
carrera gastronómica.
<br>

<!--<style>
body, td, th {
    font-family: Verdana,Geneva,sans-serif;
    font-size: 10px;
}
body {
    background-color: #414141;
}
</style>-->

