<div id="pie">
    <table width="79%" border="1" align="center" >
        <tbody>
            <tr>
                <th bgcolor="#FEFEFE" scope="col">
                    <div align="center">
                    Casilla: 665. Puerto Varas. Fono: 0-56-65-330297. E-mail:
                    <a target="_blank" href="mailto:contacto@saboresdelapatagonia.cl">contacto@saboresdelapatagonia.cl</a>
                    </div>
                </th>
            </tr>
        </tbody>
    </table>
</div>